apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: camel-runner
          image: quay.io/bstorm/camel-worker:latest
          command:
            -
#          ports:
#            - containerPort: 80
#          volumeMounts:
#            - name: camel-runner-volume
#              mountPath: /usr/share/nginx/html
      volumes:
        - name: camel-runner-volume
          configMap:
            name: ""