apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
        component: "runner-worker"
    spec:
      containers:
        - name: runner-worker
          image: ""
          command:
            -
          volumeMounts:
            - name: brainstorm-volume
              mountPath: /opt/brainstorm/data
      volumes:
        - name: runner-config-volume
          configMap:
            name: ""
        - name: brainstorm-volume
          persistentVolumeClaim:
            claimName: brainstorm-volume-claim