apiVersion: batch/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Job
metadata:
  name: ""
spec:
  template:
    metadata:
      labels:
        app: ""
        component: "sink-worker"
    spec:
      containers:
        - name: sink-runner
          image: ""
          volumeMounts:
            - name: brainstorm-volume
              mountPath: /opt/brainstorm/data
      volumes:
        - name: config-volume
          configMap:
            name: ""
        - name: brainstorm-volume
          persistentVolumeClaim:
            claimName: brainstorm-volume-claim
      restartPolicy: OnFailure