apiVersion: "pipeline.brainstorm.org/v1alpha1"
kind: Pipeline
metadata:
  name: my-test-pipeline
  namespace: default
spec:
  pipelineInfra:
    bootstrapServer: 'my-kafka-server'
    port: 9092
  sourceStep:
    image: docker.io/my-org/camel-source-runner-01:latest
  transformationSteps:
    steps:
      - image: docker.io/my-org/runner-transformer-step-01
# Just add more and more steps as needed (the operator will take care of everything else)
#      - image: docker.io/my-org/runner-worker-step-02
  sinkStep:
    image: docker.io/my-org/camel-sink-runner-01:latest
