apiVersion: "pipeline.brainstorm.org/v1alpha1"
kind: Pipeline
metadata:
  name: my-test-pipeline
  namespace: default
spec:
  pipelineInfra:
    bootstrapServer: 'my-kafka-server'
    port: 9092
  acquisitionStep:
    image: docker.io/my-org/camel-source-runner-01:latest
    producesTo: data.acquired
  transformationSteps:
    steps:
      - image: docker.io/my-org/runner-transformer-step-01
        consumesFrom: data.acquired
        producesTo: data.step.01
        name: step-01
# Just add more and more steps as needed
#      - image: docker.io/my-org/runner-worker-step-02
#        consumesFrom: data.step.01
#        producesTo: data.completed
#        name: step-02